package com.employees.springboot.entities.employee;

import java.util.List;


import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import com.employees.springboot.entities.embeddables.ContactDetails;
import com.employees.springboot.entities.embeddables.Spouse;

import org.springframework.lang.Nullable;

import com.employees.springboot.entities.embeddables.Child;
import com.employees.springboot.entities.embeddables.PrivateDetails;


import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@Entity
@Table(name="employees")
@ApiModel(description = "Employee's details")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class Employee {
    
    @Id
    @GeneratedValue
    @Column(name="id")
    @ApiModelProperty(notes = "The empID is an autoGenerated field")
    private int empId;

    @Embedded
    private PrivateDetails privateDetails;
    
    @Embedded
    private ContactDetails contactDetails;

    @Embedded
    @Nullable
    @ToString.Exclude
    private Spouse spouse;

    @Embedded
    @Nullable
    @ToString.Exclude
    private List<Child> children;

}
