package com.employees.springboot.entities.employee;

import java.util.List;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import com.employees.springboot.entities.embeddables.ContactDetails;
import com.employees.springboot.entities.embeddables.FamilyMember;
import com.employees.springboot.entities.embeddables.PrivateDetails;


import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@Entity
@Table(name="employees")
@ApiModel(description = "Employee's details")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class Employee {
    
    @Id
    @GeneratedValue
    @Column(name="id")
    @ApiModelProperty(notes = "The empID is an autoGenerated field")
    private int empId;

    @Embedded
    private PrivateDetails privateDetails;
    
    @Embedded
    private ContactDetails contactDetails;

    @Embedded
    @ToString.Exclude
    @AttributeOverrides(
        {
            @AttributeOverride( name = "firstName", column = @Column(name = "spouse_first_name")),
            @AttributeOverride( name = "age", column = @Column(name = "spouse_age")),
            @AttributeOverride( name = "identityNumber", column = @Column(name = "spouse_id"))
        }
    )
    private FamilyMember spouse;

    @Embedded
    @ToString.Exclude
    @AttributeOverrides(
        {
            @AttributeOverride( name = "firstName", column = @Column(name = "child_first_name")),
            @AttributeOverride( name = "age", column = @Column(name = "child_age")),
            @AttributeOverride( name = "identityNumber", column = @Column(name = "child_id"))
        }
    )
    private List<FamilyMember> children;

}
